version: "3.8" # Versiunea Docker Compose

services:
  backend:
    build:
      context: ./backend # Directorul în care se află codul backend
      dockerfile: Dockerfile # Numele Dockerfile-ului
    ports:
      - "5000:5000" # Mapare port local:container
    environment: # Variabilele de mediu pentru backend
      - MONGO_URI=mongodb+srv://anisoara:123%40.%40cluster0.iun7r.mongodb.net/atelierDB?retryWrites=true&w=majority
      - NODE_ENV=development
    volumes:
      - ./backend:/app # Sincronizare cod între host și container
    depends_on: # Asigură-te că MongoDB pornește înaintea backend-ului
      - mongo

  frontend:
    build:
      context: ./frontend # Directorul în care se află codul frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Mapare port local:container
    environment: # Variabilele de mediu pentru frontend
      - REACT_APP_API_URL=http://localhost:5000
    volumes:
      - ./frontend:/app

  mongo:
    image: mongo:6.0 # Imaginea oficială MongoDB
    ports:
      - "27017:27017" # Port pentru conectare locală la MongoDB (opțional)
    volumes:
      - mongo-data:/data/db # Persistent storage pentru datele MongoDB

volumes:
  mongo-data: # Declararea volumului pentru datele MongoDB
